/* limit, percentage weighting by product type
*/

EXECUTE (

	%LET LIMIT = 1000;
	%LET LIMIT_PP_MOB = &LIMIT * 0.15;
	%LET LIMIT_PT_MOB = &LIMIT * 0.40;
	%LET LIMIT_FIX_BB = &LIMIT * 0.15;
	%LET LIMIT_FIX_TEL = &LIMIT * 0.15;
	%LET LIMIT_PP_OMB = &LIMIT * 0.05;
	%LET LIMIT_PT_OMB = &LIMIT * 0.05;
	%LET LIMIT_SMB = &LIMIT * 0.05;

	DELETE FROM APAPP_CI..SAS_CI_SERV_ADHOC_DATA_ITEM
	WHERE UPPER(DATA_ITEM_CD) = UPPER('02067_CUSTOMER_MOMENT_2014')
	;
	
	CREATE TEMP TABLE APAPP_CI..IN_TABLE AS (
		SELECT DISTINCT 
			 	 S.SVC_IDNTY
				,S.MKT_PROD_CD
		FROM APAPP_CI_WORK..INTABLE_&QSYSJOBID I
		INNER JOIN APMART_FPVIEWS..FPC_SERVICE S
			ON S.SVC_IDNTY = I.SVC_IDNTY
	)
	DISTRIBUTE ON(SVC_IDNTY)
	;

	CREATE TEMP TABLE APAPP_CI..LIMIT_BY_PRODUCT AS (
		SELECT SVC_IDNTY
			,MKT_PROD_CD
		FROM (
			SELECT  
					 SVC_IDNTY
					,MKT_PROD_CD
					,CASE 
						WHEN MKT_PROD_CD IN ('HSD','DSLD') THEN 'FIX BB'
						WHEN MKT_PROD_CD IN ('LAT', 'LAD') THEN 'FIX TEL'
						ELSE MKT_PROD_CD
					END AS MKT_PROD_TYPE
					,ROW_NUMBER() OVER (PARTITION BY MKT_PROD_TYPE ORDER BY '') ORDER_BY_PRODUCT
			FROM APAPP_CI..IN_TABLE
		) FOO
		WHERE (FOO.MKT_PROD_TYPE = 'MOB PP' AND FOO.ORDER_BY_PRODUCT <= &LIMIT_PP_MOB) 
			OR (FOO.MKT_PROD_TYPE = 'MOB PT' AND FOO.ORDER_BY_PRODUCT <= &LIMIT_PT_MOB)
			OR (FOO.MKT_PROD_TYPE = 'FIX BB' AND FOO.ORDER_BY_PRODUCT <= &LIMIT_FIX_BB)
			OR (FOO.MKT_PROD_TYPE = 'FIX TEL' AND FOO.ORDER_BY_PRODUCT <= &LIMIT_FIX_TEL)
			OR (FOO.MKT_PROD_TYPE = 'OMB PP' AND FOO.ORDER_BY_PRODUCT <= &LIMIT_PP_OMB)
			OR (FOO.MKT_PROD_TYPE = 'OMB PT' AND FOO.ORDER_BY_PRODUCT <= &LIMIT_PT_OMB)
	)
	DISTRIBUTE ON(SVC_IDNTY)
	;

	INSERT INTO APAPP_CI..SAS_CI_SERV_ADHOC_DATA_ITEM
	(SVC_IDNTY,DATA_ITEM_CD,VARNAME1,VARSTRING1)
	SELECT 
	SVC_IDNTY
	,'02067_CUSTOMER_MOMENT_2014'
	,'MKT_PROD_CD'
	,MKT_PROD_CD
	FROM APAPP_CI..LIMIT_BY_PRODUCT
	;
	
) BY _LIBPASS;
