
-- TABLE FINDER
SELECT * FROM 
DBC.TABLES
WHERE TABLENAME LIKE 'YZ%' 
AND DATABASENAME = 'IPSHARE'
;

-- COLUMN FINDER
SELECT * FROM 
DBC.COLUMNS
WHERE TABLENAME LIKE 'YZ%' 
AND DATABASENAME = 'IPSHARE'
;

-- DISK SPACE OF TABLES
SELECT * 
FROM DBC.TABLES T 
INNER JOIN (
	SELECT DATABASENAME, TABLENAME, SUM(CURRENTPERM)/(1024*1024) ACTUALSPACE_MB, (MAX(CURRENTPERM)*(HASHAMP()+1))/(1024*1024) EFFECTIVESPACE_MB
	FROM DBC.TABLESIZE
	WHERE DATABASENAME = 'IPSHARE'
	GROUP BY 1,2
) DS
ON T.TABLENAME = DS.TABLENAME
AND T.DATABASENAME = DS.DATABASENAME
ORDER BY 
DS.ACTUALSPACE_MB DESC
;

-- CHECK INDICES
SELECT IND.*
  FROM DBC.INDICES IND
 WHERE
    IND.TABLENAME = 'FPH_SERVICE'
    AND IND.DATABASENAME = 'FPTABLES'
;

