
-- TABLE FINDER
SELECT * FROM 
DBC.TABLES
WHERE TABLENAME LIKE 'YZ%' 
AND DATABASENAME = 'IPSHARE'
;

-- COLUMN FINDER
SELECT * FROM 
DBC.COLUMNS
WHERE TABLENAME LIKE 'YZ%' 
AND DATABASENAME = 'IPSHARE'
;

-- DISK SPACE OF TABLES
SELECT * 
FROM DBC.TABLES T 
INNER JOIN (
	SELECT DATABASENAME, TABLENAME, SUM(CURRENTPERM)/(1024*1024) ACTUALSPACE_MB, (MAX(CURRENTPERM)*(HASHAMP()+1))/(1024*1024) EFFECTIVESPACE_MB
	FROM DBC.TABLESIZE
	WHERE DATABASENAME = 'IPSHARE'
	GROUP BY 1,2
) DS
ON T.TABLENAME = DS.TABLENAME
AND T.DATABASENAME = DS.DATABASENAME
ORDER BY 
DS.ACTUALSPACE_MB DESC
;

-- Calendar
sys_calendar.calendar

-- CHECK INDICES
SELECT IND.*
  FROM DBC.INDICES IND
 WHERE
    IND.TABLENAME = 'FPH_SERVICE'
    AND IND.DATABASENAME = 'FPTABLES'
;

-- UPDATE & QUALIFY ROW_NUMBER()
UPDATE  IPSHARE.CHURN_SAMPLE_FLAGS_20140423
FROM (
	SELECT B.SVC_IDNTY, CAST(A.DECILE AS VARCHAR(10)) AS DECILE
	FROM IPSHARE_HELIX.mus_churn_3_19_score A
	INNER JOIN IPSHARE.CHURN_SAMPLE_FLAGS_20140423 B
	ON A.SERVICE_NO = B.SVC_IDNTY
	QUALIFY ROW_NUMBER() OVER (PARTITION BY B.SVC_IDNTY ORDER BY LOAD_DT DESC) = 1
) FOO
SET POSTPAID_CHURN_DECILE = FOO.DECILE
WHERE CHURN_SAMPLE_FLAGS_20140423.SVC_IDNTY = FOO.SVC_IDNTY
;
